# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\x12\'Codespaces.Grpc.CodespaceHostService.v1\"\x13\n\x11\x45xportLogsRequest\"&\n\x12\x45xportLogsResponse\x12\x10\n\x08\x46ilePath\x18\x01 \x01(\t2\x9c\x01\n\rCodespaceHost\x12\x8a\x01\n\x0f\x45xportLogsAsync\x12:.Codespaces.Grpc.CodespaceHostService.v1.ExportLogsRequest\x1a;.Codespaces.Grpc.CodespaceHostService.v1.ExportLogsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXPORTLOGSREQUEST._serialized_start=56
  _EXPORTLOGSREQUEST._serialized_end=75
  _EXPORTLOGSRESPONSE._serialized_start=77
  _EXPORTLOGSRESPONSE._serialized_end=115
  _CODESPACEHOST._serialized_start=118
  _CODESPACEHOST._serialized_end=274
# @@protoc_insertion_point(module_scope)
